JUMA-IO/STM32_Platform

product/application/sensor_tag/app.c

1.add API app_led_control to app.c
2.send message type:0x00,length:0x01,data:0x00(LED off)/0x01(LED on)
from phone to cannon to control cannon led on/off.

Add remote LED on/off control to sensor tag application

---

product/application/echo/app.c
product/application/host/app.c
product/application/hum_temp_monitor/app.c
product/application/remote_control/app.c
product/application/sensor_tag/app.c
product/application/sensor_tag/mdk-arm/CAF.uvoptx
product/application/sensor_tag/mdk-arm/RTE/RTE_Components.h
product/application/sensor_tag_fifo/app.c
product/application/sensor_tag_fifo/mdk-arm/CAF.uvprojx
system/juma/src/stm32xx_it.c

1.fix advertise interval bug in app.c for all projects.

Fix advertise interval bug at all of the cannon projects

---

product/application/sensor_tag_fifo/app.c
product/application/sensor_tag_fifo/app.h
system/drivers/lsm303agr/LSM303AGR_MAG_driver.c
system/drivers/lsm303agr/LSM303AGR_MAG_driver.h
system/juma/inc/imu_sensor.h
system/juma/inc/imu_sensor_fusion.h
system/juma/src/bluenrg_sdk_api.c
system/juma/src/imu_sensor.c
system/juma/src/imu_sensor_fusion.c
system/juma/src/stm32xx_it.c

1.change sensor output data type
2.optimize some API
3.add clear fifo api
4.reset button bug is remained

Change imu sensor data API in sensor tag fifo project

---

product/application/sensor_tag/app.c
system/bsp/cannon_v2/stm32f4xx_cannon_v2.c
system/juma/src/juma_sensor.c

1. Remove unnecessary delay in T/H sensor API
2. Let LED Blink to show connection status
3. Send packet one by one
4. Fix wrong LED On/Off code

Improve Sensor Tag

---

.gitignore
product/application/echo/app.c
product/application/echo/mdk-arm/CAF.uvoptx
product/application/echo/mdk-arm/CAF.uvprojx
product/application/sensor_tag/mdk-arm/CAF.uvoptx
product/application/sensor_tag/mdk-arm/CAF.uvprojx
system/bsp/cannon_v2/stm32f4xx_hal_msp.c

1. Remove while(1) when there is error in fputc
2. Re-enable advertising in Echo app
3. Ignore some useless files

Fix bug that causes reconnection issue

---

system/drivers/lsm303agr/lsm303agr.c
system/juma/src/bluenrg_sdk_api.c

Use Error Handle instead of while(1)

Fix improper error handling

---

product/application/host/app.c
product/application/sensor_tag/app.c
product/application/sensor_tag/mdk-arm/CAF.uvoptx
product/application/sensor_tag/mdk-arm/CAF.uvprojx
product/application/sensor_tag_fifo/app.c

1.fix api 'adv_name_generate' sprintf bug in application

Fix advertise generate API word bug in application

---

product/application/sensor_tag_fifo/app.c
product/application/sensor_tag_fifo/app.h
product/application/sensor_tag_fifo/mdk-arm/CAF.uvoptx
product/application/sensor_tag_fifo/mdk-arm/CAF.uvprojx
system/juma/inc/imu_sensor.h
system/juma/inc/imu_sensor_fusion.h
system/juma/src/imu_sensor.c
system/juma/src/imu_sensor_fusion.c
system/juma/src/main.c

1.add imu_sensor_fusion_1
2.app.c send pitch , roll, yaw angle to phone per 110ms by BLE

Add imu_sensor_fusion_1 API to  sensor_tag_fifo in application

---

product/application/toolbox/MDK-ARM/CAF.uvoptx
product/application/toolbox/MDK-ARM/CAF.uvprojx
product/application/toolbox/app.c

The previous version project has some mistakes.

Update toolbox project.

---

product/application/host/app.c
product/application/host/app.h
product/application/host/mdk-arm/CAF.uvoptx
product/application/host/mdk-arm/CAF.uvprojx
system/juma/inc/bluenrg_sdk_api.h
system/juma/inc/bluenrg_sdk_host_api.h
system/juma/src/bluenrg_sdk_api.c
system/juma/src/bluenrg_sdk_api_host.c
system/juma/src/main.c

1.move host code from bluenrg_sdk_api.c to new folder
bluenrg_sdk_host_api
2.chang some host api
3.use dispatcher to improve host connection initial procession.

Adjust host mode code structure .

---

product/application/host/mdk-arm/CAF.uvoptx
product/application/host/mdk-arm/CAF.uvprojx
system/juma/inc/bluenrg_sdk_api.h
system/juma/inc/bluenrg_sdk_host_api.h
system/juma/src/bluenrg_sdk_api.c

1.adjuest bluenrg_sdk_api.c and bluenrg_sdk_host_api.c api

Adjust bluenrg_sdk_api.c and bluenrg_sdk_host_api.c api

---

product/application/echo/app.c
product/application/echo/mdk-arm/CAF.uvoptx
product/application/echo/mdk-arm/CAF.uvprojx
product/application/host/mdk-arm/CAF.uvoptx
product/application/host/mdk-arm/CAF.uvprojx
product/application/hum_temp_monitor/app.c
product/application/hum_temp_monitor/mdk-arm/CAF.uvoptx
product/application/remote_control/app.c
product/application/remote_control/mdk-arm/CAF.uvoptx
product/application/remote_control/mdk-arm/RTE/RTE_Components.h
product/application/sensor_tag/mdk-arm/CAF.uvprojx
product/application/sensor_tag_fifo/mdk-arm/CAF.uvoptx
product/application/sensor_tag_fifo/mdk-arm/CAF.uvprojx
system/bsp/nucleo/x_nucleo_iks01a1.c
system/drivers/bluenrg/inc/hal.h
system/drivers/bluenrg/src/hci.c
system/drivers/lsm303agr/lsm303agr.c
system/drivers/stm32f4xx_hal_driver/src/stm32f4xx_hal_spi.c
system/juma/src/bluenrg_sdk_api.c
system/juma/src/dispatch.c
system/juma/src/imu_sensor.c
system/juma/src/imu_sensor_fusion.c
system/juma/src/juma_sensor.c
system/juma/src/stm32f401_lp_mode.c

1.fix all warning except for two '__packet' warning in
stm32f4xx_ll_usb.c

Fix all warning except for two '__packet' warning in stm32f4xx_ll_usb.c

---

product/application/sensor_tag/mdk-arm/CAF.uvoptx
system/juma/src/bluenrg_sdk_api.c
system/juma/src/main.c

1.change the internal function ble_int_bluenrg of bluenrg_sdk_api.c  to
be called by main.c  from app.c.

Change the internal function ble_init_bluenrg   to be called by main

---

product/application/gravity_filter/app.c
system/juma/inc/imu_sensor.h
system/juma/inc/imu_sensor_fusion.h
system/juma/src/imu_sensor_fusion.c

1. improve zero motion detection logics
2. dynamic error correction gain

enhance gravity filter

---

system/juma/src/main.c

1.Add Macro 'LOW_POWER_MODE' to switch on/off mcu low power mode in
main.c

Add Macro 'LOW_POWER_MODE' to switch on/off mcu low power mode in main.c

---

product/application/juma/9-axis-sensor_fifo_int/mdk-arm/CAF.uvprojx
product/application/juma/FatFs/mdk-arm/CAF.uvprojx
product/application/juma/echo/mdk-arm/CAF.uvprojx
product/application/juma/gravity_filter/mdk-arm/CAF.uvprojx
product/application/juma/host/app.c
product/application/juma/host/mdk-arm/CAF.uvprojx
product/application/juma/hum_temp_monitor/mdk-arm/CAF.uvprojx
product/application/juma/mesh/app.c
product/application/juma/mesh/mdk-arm/CAF.uvprojx
product/application/juma/pwm/mdk-arm/CAF.uvprojx
product/application/juma/remote_control/mdk-arm/CAF.uvprojx
product/application/juma/sensor_tag/mdk-arm/CAF.uvprojx
product/application/juma/sensor_tag_fifo/mdk-arm/CAF.uvprojx
product/application/juma/toolbox/mdk-arm/CAF.uvprojx
product/application/juma/usb/mdk-arm/CAF.uvprojx
system/middlewares/juma/main.c
system/middlewares/juma/mesh/mesh.c
system/middlewares/juma/mesh/mesh.h
system/middlewares/juma/sdk/bluenrg_sdk_api.c
system/middlewares/juma/sdk/bluenrg_sdk_api.h
system/middlewares/juma/sdk/bluenrg_sdk_api_host.c
system/middlewares/juma/sdk/bluenrg_sdk_host_api.h

1.Optimize bluenrg sdk api in bluenrg_sdk_api.c  2.Add macro SERVER_ROLE to all application in product/application/juma

1.Optimize bluenrg sdk api in bluenrg_sdk_api.c  2.Add macro SERVER_ROLE to all application in product/application/juma

---

system/middlewares/juma/stm32xx_it.c

Fix compile error in stm32xx_it.c

Fix compile error in stm32xx_it.c

---

system/bsp/cannon_v2/stm32f4xx_hal_msp.c
system/bsp/cannon_v2/stm32f4xx_hal_msp.h
system/bsp/nucleo/x_nucleo_iks01a1.c
system/bsp/nucleo/x_nucleo_iks01a1.h
system/bsp/nucleo/x_nucleo_iks01a1_hum_temp.c
system/bsp/nucleo/x_nucleo_iks01a1_pressure.c
system/drivers/st/hts221/hts221.c
system/drivers/st/lps25h/lps25h.c
system/drivers/st/lps25hb/lps25hb.c
system/drivers/st/lsm303agr/LSM303AGR_ACC_driver.c
system/drivers/st/lsm303agr/LSM303AGR_ACC_driver.h
system/drivers/st/lsm303agr/LSM303AGR_MAG_driver.c
system/drivers/st/lsm6ds3/lsm6ds3.c
system/drivers/st/lsm6ds3/lsm6ds3.h
system/middlewares/juma/sdk/bluenrg_sdk_api.c
system/middlewares/st/bluenrg_ms/inc/hal.h
system/middlewares/st/bluenrg_ms/src/hci.c
system/middlewares/st/bluenrg_ms/src/list.c

Modified program not only to be compiled by C99 but also to be compiled by CPP11

 Modified program not only to be compiled by C99 but also to be compiled by CPP11

---

engine/README.md
engine/micropython/CANNON_V2/README.md
engine/micropython/CANNON_V2/hts221.py

HTS221 drive

---

engine/micropython/CANNON_V2/hts221/README.md
engine/micropython/CANNON_V2/hts221/hts221.py
engine/micropython/CANNON_V2/lps25h/README.md
engine/micropython/CANNON_V2/lps25h/lps25h.py

* move HTS221 to hts221 folder
+ LPS25H drive
+ add Device identification function in hts221 drive

Add LPS25H drive
